### ISSUE TITLE
LICENCE.TXT removes original copyright notice / LICENCE.TXT удаляет оригинальное уведомление об авторских правах

### ISSUE THREAD

**Issue by 0x6273** [ss14-ganimed/GS14-Master#10]
### Описание

Hi. Sorry, but I do not speak Russian. You have removed the line `Copyright (c) 2017-2023 Space Wizards Federation`, which is not allowed by the MIT license.

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Instead, please add your own copyright on a separate line. For example:

```
MIT License

Copyright (c) 2017-2023 Space Wizards Federation
Copyright (c) 2022-2023 Ganimed Team
```

## Google translate / Google Переводчик:

Привет. Извините, но я не говорю по-русски. Вы удалили строку «Copyright (c) 2017-2023 Space Wizards Federation», что не разрешено лицензией MIT.

> Вышеприведенное уведомление об авторских правах и это уведомление о разрешении должны быть включены во все
копии или существенные части Программного обеспечения.

Вместо этого укажите свои авторские права в отдельной строке. Например:

```
MIT License

Copyright (c) 2017-2023 Space Wizards Federation
Copyright (c) 2022-2023 Ganimed Team
```

**Comment by Yuoko** [comment]
> ### Описание
> Hi. Sorry, but I do not speak Russian. You have removed the line `Copyright (c) 2017-2023 Space Wizards Federation`, which is not allowed by the MIT license.
> 
> > The above copyright notice and this permission notice shall be included in all
> > copies or substantial portions of the Software.
> 
> Instead, please add your own copyright on a separate line. For example:
> 
> ```
> MIT License
> 
> Copyright (c) 2017-2023 Space Wizards Federation
> Copyright (c) 2022-2023 Ganimed Team
> ```
> 
> ## Google translate / Google Переводчик:
> Привет. Извините, но я не говорю по-русски. Вы удалили строку «Copyright (c) 2017-2023 Space Wizards Federation», что не разрешено лицензией MIT.
> 
> > Вышеприведенное уведомление об авторских правах и это уведомление о разрешении должны быть включены во все
> > копии или существенные части Программного обеспечения.
> 
> Вместо этого укажите свои авторские права в отдельной строке. Например:
> 
> ```
> MIT License
> 
> Copyright (c) 2017-2023 Space Wizards Federation
> Copyright (c) 2022-2023 Ganimed Team
> ```
> 
> ### Шаги воспроизведения (только для ошибок)
> _No response_
> 
> ### Скриншоты (референсы/скрины ошибки)
> _No response_

Excuse me. We didn't notice this in the license, we are already correcting it.
