### ISSUE TITLE
Баг репорт перед обновой

### ISSUE THREAD

**Issue by Yuoko** [ss14-ganimed/GS14-Master#35]
### Описание

Прикладываю скриншоты и описания всевозможных багов которые должны быть исправлены ДО выпуска обновы.
- [ ] Все баги приложеные в скриншотах:

- [ ] #36
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/145a0df0-9cef-48b9-a63a-cd4ffa937fa3)

- [x] **[ИСПРАВЛЕНО]** Нет иконок для SecurityHUDа для NanoTrasen Official (ЦК)

- [ ] #39

- [X] **[ИСПРАВЛЕНО]** Отсутствуют многие переводы (например такси-бот и многие модули боргов и тд)

- [ ] #40
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/43a27cbb-11bf-45ab-a04d-ee917747c082)

### Скриншоты (референсы/скрины ошибки)

 - [X] **[ИСПРАВЛЕНО]** нет перевода роли:
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/13c85713-5a7f-474b-b517-f2c282497a69)
- [ ] #41
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/60d09fe1-59ba-4d2d-8a2e-5ef674578135)
- [X] **[ИСПРАВЛЕНО]** нет перевода на таблицах-указателях:
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/cf961d0e-24e0-48da-9ab2-b675e7936edd)
- [ ] #42
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/692c59d6-8c1a-4fdc-881b-669bbe5337f4)
- [X] **[ИСПРАВЛЕНО]** Нет иконок для цк в охранном визоре
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/d6b595ee-91a4-41b8-9a16-5294b2caf29a)
- [x] **[ИСПРАВЛЕНО]** Отсутствует перевод:
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/d6e4b3cb-d9e2-441d-b35d-906f037f45f8)
- [X] **[ИСПРАВЛЕНО]** Некоректный перевод ID карт под изменённые названия должностей:
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/7728904a-ee42-414d-b6dd-62310c12ffba)
- [X] **[ИСПРАВЛЕНО]** Отсутствует перевод:
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/35a14016-f493-4bd3-b72b-c9390554e3a0)
- [X] **[ИСПРАВЛЕНО]** Некорректные переводы вещей ментор ролей:
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/bbe9d4be-7895-429c-85d5-7b0bcf9a2a19)
- [x] **[ИСПРАВЛЕНО]** Шлюз квартирмейстера имеет спрайт командования (должен иметь спрайт карго)
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/6e32aa00-e281-4460-ab1f-2c376e22de02)
- [x] **[ИСПРАВЛЕНО]** Отсутствие перевода:
![image](https://github.com/ss14-ganimed/GS14-Master/assets/128321596/203a2d0b-32be-4265-bf3e-b24dc756c5b6)

**Comment by temporaldarkness** [comment]
Основная часть проблем исправлена, остальное разделено на отдельные задачи, которые будут решены в будущем.
